package com.squadstack.parkinglot.exception;

public enum ErrorCode {

    INVALID_FILEPATH_EXCEPTION,
    SLOTS_UNAVAILABLE_EXCEPTION,
    INVALID_AGE,
    INVALID_COMMAND,
    CAR_PLATE_NOT_PRESENT,
    ATTEMPT_TO_LEAVE_UNACQUIRED_SLOT,
    INVALID_SLOT_NUMBER


    ;
}
